version: "3.9"
services:
  web:
    image: ex_webi             # image name
    container_name: ex_webc    # container name
    build: ./web               # source location
    ports: 
      - "5056:5056"            # 172.20.0.5
  web2:
    image: ex_webi2
    container_name: ex_webc2
    build: ./web2
    ports: 
      - "5057:5057"

  mysql:
    image: mysql
    container_name: ex_mysqlc
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test-db
    ports:
      - 5058:3306
    
  mysql-admin:
    image: adminer
    container_name: ex_adminerc
    restart: always
    ports:
      - "5059:8080"

# System: MySQL <DB System to connect>
# Server: mysql <should match the starting tag before image tag > (in your case mysql but you can change it to any name )
# Username: root <username>
# Password: <password>
# Database: db <database name>